### ISSUE TITLE
การแสดงผลในหน้ารวมสินค้าเบี้ยว

### ISSUE THREAD

**Issue by ploeauer** [puttio/getkaset-webapp#10]
![1](https://cloud.githubusercontent.com/assets/12734578/7979698/add68b1a-0acb-11e5-9f35-87d6d69911e5.png)

ให้แสดงผลตามลำดับด้วยได้มั้ยพุทธิเช่นลงประกาศที่หลังประกาศนั้นก็ตกลงไปเรื่อยๆ

**Comment by puttio** [comment]
working on it
