### ISSUE TITLE
ปุ่มลงลงประกาศด้วยมือถือ

### ISSUE THREAD

**Issue by ploeauer** [puttio/getkaset-webapp#9]
ปุ่มลงลงประกาศด้วยมือถือ บางคนเข้าเว็บมาอาจจะงงๆ เพราะไม่มีปุ่มลงประกาศเวลาดูด้วยมือถือ ต้องกดไปที่ปุ่มขวามือขีดๆด้านบน แต่ถ้าเข้าผ่าน PC  โอเคแล้ว

**Comment by puttio** [comment]
done
